# API Adapter - Quote
Demo tự động các hàm trong class `Quote`.

In [2]:
from vnstock_data.api.quote import Quote

# Khởi tạo instance
instance = Quote(source='KBS', symbol='VNM')

### `history()`
Load historical OHLC data for the symbol.

In [5]:
df_history = instance.history(length=30)
display(df_history)

                  time  open  high   low  close   volume
0  2026-03-11 07:00:00  61.7  63.7  61.6   63.0  7507500
1  2026-03-12 07:00:00  62.0  62.7  61.3   61.6  6298800
2  2026-03-13 07:00:00  62.0  63.2  61.6   63.1  5388500
3  2026-03-16 07:00:00  62.6  62.9  61.7   61.8  2965000
4  2026-03-17 07:00:00  62.7  63.0  61.5   61.5  3816100
5  2026-03-18 07:00:00  61.8  62.7  61.6   61.7  2596400
6  2026-03-19 07:00:00  61.4  62.0  60.8   61.0  6400100
7  2026-03-20 07:00:00  61.0  61.5  60.0   60.0  5734800
8  2026-03-23 07:00:00  59.2  61.0  59.2   60.8  5908000
9  2026-03-24 07:00:00  61.8  61.8  60.9   61.2  2689900
10 2026-03-25 07:00:00  61.5  62.2  61.4   62.1  3445600
11 2026-03-26 07:00:00  62.1  62.1  61.0   61.0  2044000
12 2026-03-27 07:00:00  61.0  61.9  60.9   61.5  2137400
13 2026-03-30 07:00:00  60.6  61.5  60.2   60.6  4075600
14 2026-03-31 07:00:00  61.0  61.5  60.5   60.5  5323200
15 2026-04-01 07:00:00  61.3  62.2  61.0   61.3  5446200
16 2026-04-02 07:00:00  61.5  61.7  60.8   60.8  2855300
17 2026-04-03 07:00:00  61.0  61.7  60.0   60.0  3788600
18 2026-04-06 07:00:00  60.0  61.0  60.0   60.9  2587400
19 2026-04-07 07:00:00  60.9  61.2  60.3   61.0  1825200
20 2026-04-08 07:00:00  62.2  62.7  61.7   62.6  5568500
21 2026-04-09 07:00:00  61.8  62.1  61.4   61.8  2921000
22 2026-04-10 07:00:00  62.6  64.0  62.5   62.8  6158400

### `intraday()`
Load intraday trade data for the symbol.

In [6]:
df_intraday = instance.intraday()
display(df_intraday)

,time,price,volume,match_type,id
999,2026-04-10 10:44:18,63.2,100,sell,2026-04-10_104418_632000_100
998,2026-04-10 10:44:23,63.3,100,buy,2026-04-10_104423_633000_100
997,2026-04-10 10:44:38,63.2,3800,sell,2026-04-10_104438_632000_3800
996,2026-04-10 10:45:00,63.2,500,sell,2026-04-10_104500_632000_500
995,2026-04-10 10:45:07,63.2,200,sell,2026-04-10_104507_632000_200
...,...,...,...,...,...
4,2026-04-10 14:29:37,62.6,800,sell,2026-04-10_142937_626000_800
3,2026-04-10 14:29:50,62.6,100,sell,2026-04-10_142950_626000_100
2,2026-04-10 14:29:58,62.7,1000,buy,2026-04-10_142958_627000_1000
1,2026-04-10 14:45:24,62.8,142300,atc,2026-04-10_144524_628000_142300
0,2026-04-10 14:45:24,62.8,153400,,2026-04-10_144524_628000_153400

### `price_depth()`
Load price depth (order book) data for the symbol.

In [7]:
df_price_depth = instance.price_depth()
display(df_price_depth)

    price  buyVol  sellVol  unknownVol  totalVol
0   62500       0     8400           0      8400
1   62600   24900   254700      108300    387900
2   62700  168000   178800           0    346800
3   62800  110900   126700      295700    533300
4   62900  130700   108400           0    239100
5   63000  155200    80200           0    235400
6   63100   37700   157400           0    195100
7   63200  416600   707900           0   1124500
8   63300  357300   317400           0    674700
9   63400  294300   331300           0    625600
10  63500  258700   108700           0    367400
11  63600  187200   144800           0    332000
12  63700  394900   257400           0    652300
13  63800  263100    41200           0    304300
14  63900   74500    45900           0    120400
15  64000   11200        0           0     11200