# API Adapter - Company
Demo tự động các hàm trong class `Company`.

In [19]:
from vnstock_data.api.company import Company

# Khởi tạo instance
instance = Company(source='VCI', symbol='VNM')

### `affiliate()`
Retrieve company affiliate data.

In [20]:
df_affiliate = instance.affiliate()
display(df_affiliate)

,id,sub_organ_code,organ_name,ownership_percent
0,29026516,APIS,Công ty Cổ phần APIS,0.2000
1,29026517,ASIACOCONUT,Công ty Cổ phần Chế Biến Dừa Á Châu,0.2496
2,29026518,F000001208,Miraka Holding Limited,0.1355

### `capital_history()`
Retrieve company charter capital history.

In [21]:
df_capital_history = instance.capital_history()
display(df_capital_history)

RetryError: RetryError[<Future at 0x1222e4850 state=finished raised NotImplementedError>]

### `events()`
Retrieve company events.

In [ ]:
df_events = instance.events()
display(df_events)

Empty DataFrame
Columns: []
Index: []

### `news()`
Retrieve company news.

In [ ]:
df_news = instance.news()
display(df_news)

,head,article_id,title,publish_time,url
0,"Trong bối cảnh thị trường đầy biến động, khả n...",1413395,Vị thế tiền mặt ròng là gì và ai đang đứng đầu...,2026-03-18T11:02:00,/2026/03/vi-the-tien-mat-rong-la-gi-va-ai-dang...

### `officers()`
Retrieve company officers data.

In [ ]:
df_officers = instance.officers()
display(df_officers)

,from_date,position,name,position_en,owner_code
0,TV Độc lập,CTHĐQT,Ông Nguyễn Hạnh Phúc,CTHĐQT (Chairman of BOD),CTHĐQT
1,TV Độc lập,TVHĐQT/Chủ tịch Ủy ban Kiểm toán,Ông Đỗ Lê Hùng,TVHĐQT (Member of BOD),TVHĐQT
2,2018,TVHĐQT/TV Ủy ban Kiểm toán,Ông Alain Xavier Cany,TVHĐQT (Member of BOD),TVHĐQT
3,2017,TVHĐQT/TV Ủy ban Kiểm toán,Bà Đặng Thị Thu Hà,TVHĐQT (Member of BOD),TVHĐQT
4,2017,TVHĐQT/TV Ủy ban Kiểm toán,Ông Michael Chye Hin Fah,TVHĐQT (Member of BOD),TVHĐQT
5,1994,TVHĐQT/GĐ Tài chính,Ông Lê Thành Liêm,TVHĐQT (Member of BOD),TVHĐQT
6,1976,TGĐ/TVHĐQT,Bà Mai Kiều Liên,TGĐ (CEO),TGĐ
7,TV Độc lập,TVHĐQT,Bà Tiêu Yến Trinh,TVHĐQT (Member of BOD),TVHĐQT
8,2025,TVHĐQT,Bà Tongjai ThanaCHanan,TVHĐQT (Member of BOD),TVHĐQT
9,2025,TVHĐQT,Ông Vũ Trí Thức,TVHĐQT (Member of BOD),TVHĐQT
10,2005,GĐ Điều hành,Bà Bùi Thị Hương,GĐ Điều hành (Executive Director),GĐ Điều hành
11,1999,GĐ Điều hành,Ông Đoàn Quốc Khánh,GĐ Điều hành (Executive Director),GĐ Điều hành
12,N/A,GĐ Điều hành,Ông Lê Hoàng Minh,GĐ Điều hành (Executive Director),GĐ Điều hành
13,N/A,GĐ Điều hành,Ông Nguyễn Quang Trí,GĐ Điều hành (Executive Director),GĐ Điều hành
14,2009,GĐ Điều hành,Ông Nguyễn Quốc Khánh,GĐ Điều hành (Executive Director),GĐ Điều hành
15,N/A,KTT,Bà Huỳnh Thị Phương Lan,KTT (Chief Accountant),KTT

### `overview()`
Retrieve company overview data.

In [ ]:
df_overview = instance.overview()
display(df_overview)

,business_model,symbol,founded_date,charter_capital,number_of_employees,listing_date,par_value,exchange,listing_price,listed_volume,...,phone,fax,email,website,branches,history,free_float_percentage,free_float,outstanding_shares,as_of_date
0,"\n- Chế biến, sản xuất kinh doanh sữa và các s...",VNM,01/10/2003,20900,9906,19/01/2006,10000,HOSE,53000,2090,...,(84.28) 5415 5555,(84.28) 5416 1226 - 5416 1230,vinamilk@vinamilk.com.vn,https://www.vinamilk.com.vn,- Tại Hà Nội: 57 Trần Duy Hưng - P. Trung Hòa ...,\n- Năm 1976: Tiền thân của công ty là Công ty...,20899554450000,10000,2089955445,2025-12-31T00:00:00

### `shareholders()`
Retrieve company shareholders data.

In [ ]:
df_shareholders = instance.shareholders()
display(df_shareholders)

,name,update_date,shares_owned,ownership_percentage
0,Tổng Công ty Đầu tư và Kinh doanh Vốn Nhà nước,2025-08-29T00:00:00,752476602,36.00
1,F&N Dairy Investments Pte Ltd,2025-12-22T00:00:00,465847490,22.29

### `subsidiaries()`
Retrieve company subsidiaries data.

In [ ]:
df_subsidiaries = instance.subsidiaries()
display(df_subsidiaries)

,update_date,name,charter_capital,ownership_percent,currency,type
0,2025-12-31T00:00:00,Công ty TNHH MTV Bò Sữa Thống Nhất Thanh Hóa,-1,100.00,,công ty con
1,2025-12-31T00:00:00,Driftwood Dairy Holding Corporation,-1,100.00,,công ty con
2,2025-12-31T00:00:00,"Angkor Dairy Products Co., Ltd",-1,100.00,,công ty con
3,2025-12-31T00:00:00,Công ty TNHH MTV Bò Sữa Việt Nam,-1,100.00,,công ty con
4,2025-12-31T00:00:00,Công ty TNHH MTV Bò Sữa Thống Nhất Thanh Hóa,-1,100.00,,công ty con
5,2025-12-31T00:00:00,"Angkor Dairy Products Co., Ltd",-1,100.00,,công ty con
6,2025-12-31T00:00:00,Công ty TNHH MTV Bò Sữa Việt Nam,-1,100.00,,công ty con
7,2025-12-31T00:00:00,"Lao-Jagro Development XiengKhouang Co., Ltd",-1,92.07,,công ty con
8,2025-12-31T00:00:00,Tổng Công ty Chăn nuôi Việt Nam - CTCP,-1,68.94,,công ty con
9,2025-12-31T00:00:00,Tổng Công ty Chăn nuôi Việt Nam - CTCP,-1,68.94,,công ty con
10,2025-12-31T00:00:00,CTCP Đường Việt Nam,-1,65.00,,công ty con
11,2025-12-31T00:00:00,CTCP Giống Bò sữa Mộc Châu,-1,49.73,,công ty liên kết
12,2025-12-31T00:00:00,Công ty TNHH Chăn nuôi Việt Nhật,-1,35.16,,công ty liên kết
13,2025-12-31T00:00:00,CTCP Chế biến Dừa Á Châu,-1,24.96,,công ty liên kết
14,2025-12-31T00:00:00,CTCP APIS,-1,20.00,,công ty liên kết
15,2025-12-31T00:00:00,Miraka Holding Limited,-1,13.55,,công ty liên kết