# API Adapter - Finance
Demo tự động các hàm trong class `Finance`.

In [23]:
from vnstock_data.api.financial import Finance

# Khởi tạo instance
instance = Finance(source='vci', symbol='VNM')

### `balance_sheet()`
Retrieve balance sheet data.

In [16]:
df_balance_sheet = instance.balance_sheet(period='quarter')
display(df_balance_sheet)

,item,item_id,2025-Q4,2025-Q3,2025-Q2,2025-Q1
0,TÀI SẢN,assets,NaN,NaN,NaN,NaN
1,A. TÀI SẢN NGẮN HẠN,a_short_term_assets,3.626118e+10,3.874685e+10,3.825509e+10,3.840799e+10
2,I. Tiền và các khoản tương đương tiền,i_cash_and_cash_equivalents,1.794880e+09,5.154466e+09,2.498443e+09,2.538024e+09
3,1. Tiền,1_cash,1.630880e+09,1.427466e+09,2.137443e+09,1.228704e+09
4,2. Các khoản tương đương tiền,2_cash_equivalents,1.640000e+08,3.727000e+09,3.610000e+08,1.309320e+09
...,...,...,...,...,...,...
119,II. Nguồn kinh phí và quỹ khác,ii_other_resources_and_funds,NaN,NaN,NaN,NaN
120,1. Nguồn kinh phí,1_subsidized_not_for_profit_funds,NaN,NaN,NaN,NaN
121,2. Nguồn kinh phí đã hình thành TSCĐ,2_funds_invested_in_fixed_assets,NaN,NaN,NaN,NaN
122,C. LỢI ÍCH CỔ ĐÔNG THIỂU SỐ,c_minority_s_interest,NaN,NaN,NaN,NaN
123,TỔNG CỘNG NGUỒN VỐN,total_owner_s_equity_and_liabilities,5.331237e+10,5.567782e+10,5.528266e+10,5.501379e+10

### `cash_flow()`
Retrieve cash flow statement data.

In [20]:
df_cash_flow = instance.cash_flow(period='quarter')
display(df_cash_flow)

,item,item_id,2025-Q1
0,I. Lưu chuyển tiền từ hoạt động kinh doanh,i_cash_flows_from_operating_activities,NaN
1,1. Lợi nhuận trước thuế,1_profit_before_tax,1.951296e+09
2,2. Điều chỉnh cho các khoản,2_adjustments_for,NaN
3,Khấu hao TSCĐ và BĐSĐT,depreciation_of_fixed_assets_and_properties_in...,5.117912e+08
4,Các khoản dự phòng,reversal_of_provisions_provisions,2.485757e+06
5,"Lãi, lỗ chênh lệch tỷ giá hối đoái do đánh giá...",foreign_exchange_gain_loss_from_revaluation_of...,4.698502e+06
6,"Lãi, lỗ từ hoạt động đầu tư",loss_profit_from_investment_activities,-3.431853e+08
7,Chi phí lãi vay,interest_expense,7.515521e+07
8,"Lãi, lỗ từ thanh lý TSCĐ",loss_profits_from_disposal_of_fixed_asset,NaN
9,Thu nhập lãi vay và cổ tức,interest_income_and_dividends,NaN
10,Phân bổ lợi thế thương mại,allocation_of_goodwill,6.081978e+07
11,Điều chỉnh cho các khoản khác,adjustments_for,NaN
12,3. Lợi nhuận từ hoạt động kinh doanh trước tha...,3_operating_profit_before_changes_in_working_c...,2.263061e+09
13,"Tăng, giảm các khoản phải thu",increase_decrease_in_receivables,9.159227e+08
14,"Tăng, giảm hàng tồn kho",increase_decrease_in_inventories,-1.409386e+09
15,"Tăng, giảm các khoản phải trả (không kể lãi va...",increase_decrease_in_payables_other_than_inter...,-4.298664e+08
16,"Tăng, giảm chi phí trả trước",increase_decrease_in_prepaid_expenses,-6.194934e+07
17,"Tăng, giảm chứng khoán kinh doanh",changes_in_available_for_sale_securities,NaN
18,Tiền lãi vay đã trả,interest_paid,-5.888010e+07
19,Thuế thu nhập doanh nghiệp đã nộp,corporate_income_tax_paid,-9.318631e+08
20,Tiền thu khác từ hoạt động kinh doanh,other_receipts_from_operating_activities,NaN
21,Tiền chi khác cho hoạt động kinh doanh,other_payments_for_operating_activities,-4.117540e+08
22,Lưu chuyển tiền thuần từ hoạt động kinh doanh,net_cash_flows_from_operating_activities,-1.247148e+08
23,II. Lưu chuyển tiền từ hoạt động đầu tư,ii_cash_flows_from_investing_activities,NaN
24,"1. Tiền chi để mua sắm, xây dựng TSCĐ và các t...",1_payment_for_fixed_assets_constructions_and_o...,-4.170184e+08
25,"2. Tiền thu từ thanh lý, nhượng bán TSCĐ và cá...",2_receipts_from_disposal_of_fixed_assets_and_o...,2.569754e+07
26,"3. Tiền chi cho vay, mua các công cụ nợ của đơ...",3_loans_purchases_of_other_entities_debt_instr...,NaN
27,"4. Tiền thu hồi cho vay, bán lại các công cụ n...",4_receipts_from_loan_repayments_sale_of_other_...,7.748297e+08
28,5. Tiền chi đầu tư góp vốn vào đơn vị khác,5_payments_for_investment_in_other_entities,NaN
29,6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác,6_collections_on_investment_in_other_entities,9.833160e+05
30,"7. Tiền thu lãi cho vay, cổ tức và lợi nhuận đ...",7_dividends_interest_and_profit_received,1.579818e+08
31,8. Tăng giảm tiền gửi ngân hàng có kỳ hạn,8_increase_decrease_in_term_deposit,NaN
32,9. Mua lại khoản góp vốn của cổ đông thiểu số ...,9_purchases_of_minority_shares_of_subsidiaries,NaN
33,10. Tiền thu khác từ hoạt động đầu tư,10_other_receipts_from_investing_activities,NaN
34,11. Tiền chi khác cho hoạt động đầu tư,11_other_payments_for_investing_activities,NaN
35,Lưu chuyển tiền thuần từ hoạt động đầu tư,net_cash_flows_from_investing_activities,5.424740e+08
36,III. Lưu chuyển tiền từ hoạt động tài chính,iii_cash_flows_from_financing_activities,NaN
37,"1. Tiền thu từ phát hành cổ phiếu, nhận vốn gó...",1_receipts_from_equity_issue_and_owner_s_capit...,NaN
38,"2. Tiền chi trả vốn góp cho các chủ sở hữu, mu...",2_payment_for_share_repurchases,NaN
39,3. Tiền thu từ đi vay,3_proceeds_from_borrowings,4.902421e+09
40,4. Tiền trả nợ gốc vay,4_principal_repayments,-3.963677e+09
41,5. Tiền trả nợ gốc thuê tài chính,5_repayment_of_financial_leases,-1.044978e+09
42,"6. Cổ tức, lợi nhuận đã trả cho chủ sở hữu",6_dividends_paid_profits_distributed_to_owners,NaN
43,7. Tiền thu khác từ hoạt động tài chính,7_other_receipts_from_financing_activities,NaN
44,8. Tiền chi khác cho hoạt động tài chính,8_other_payments_for_financing_activities,NaN
45,Lưu chuyển tiền thuần từ hoạt động tài chính,net_cash_flows_from_financing_activities,-1.062339e+08
46,Lưu chuyển tiền thuần trong kỳ,net_cash_flows_during_the_period,3.115253e+08
47,Tiền và tương đương tiền đầu kỳ,cash_and_cash_equivalents_at_beginning_of_the_...,2.225944e+09
48,Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi...,exchange_difference_due_to_re_valuation_of_end...,5.553320e+05
49,Tiền và tương đương tiền cuối kỳ,cash_and_cash_equivalents_at_end_of_the_period,2.538024e+09

### `income_statement()`
Retrieve income statement data.

In [28]:
df_income_statement = instance.income_statement(period='quarter')
display(df_income_statement)

,report_period,ticker,Sales,Sales deductions,Net sales,Cost of sales,Gross Profit,Financial income,Financial expenses,Interest expenses,...,isb33,isb34,isb35,isb36,isb37,isb38,isb39,isb40,isb41,Gain/(loss) from joint ventures (from 2015)
period,,,,,,,,,,,,,,,,,,,,,
2018-Q1,quarter,VNM,1.213196e+13,-1.146168e+10,1.212050e+13,-6.633809e+12,5.486693e+12,1.902572e+11,-1.931417e+10,-8.555584e+09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.406185e+10
2018-Q2,quarter,VNM,1.373845e+13,-3.596526e+10,1.370248e+13,-7.233870e+12,6.468611e+12,2.046822e+11,-4.326922e+10,-1.727201e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.581958e+09
2018-Q3,quarter,VNM,1.374350e+13,-8.238352e+09,1.373526e+13,-7.241743e+12,6.493517e+12,1.856250e+11,-3.021411e+10,-1.198179e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.434257e+09
2018-Q4,quarter,VNM,1.301532e+13,-1.161516e+10,1.300371e+13,-6.841122e+12,6.162585e+12,1.793530e+11,-2.520949e+10,-1.355804e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.151957e+10
2019-Q1,quarter,VNM,1.323008e+13,-4.078443e+10,1.318930e+13,-7.034298e+12,6.155003e+12,1.762874e+11,-2.876820e+10,-1.983552e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.260770e+10
2019-Q2,quarter,VNM,1.461040e+13,-1.144107e+10,1.459896e+13,-7.585015e+12,7.013946e+12,1.907200e+11,-4.215277e+10,-2.535515e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.474049e+09
2019-Q3,quarter,VNM,1.430404e+13,-1.314255e+10,1.429090e+13,-7.567934e+12,6.722966e+12,2.067327e+11,-4.489519e+10,-2.779583e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-9.779648e+09
2019-Q4,quarter,VNM,1.425570e+13,-1.673892e+10,1.423896e+13,-7.558659e+12,6.680303e+12,2.335766e+11,-7.115352e+10,-3.583840e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.419671e+10
2020-Q1,quarter,VNM,1.420619e+13,-5.309207e+10,1.415310e+13,-7.547288e+12,6.605812e+12,2.848797e+11,-1.224287e+11,-4.206154e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.178971e+10
2020-Q2,quarter,VNM,1.550959e+13,-1.435241e+10,1.549523e+13,-8.357339e+12,7.137895e+12,3.353515e+11,-6.743839e+08,-3.764185e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.327202e+09
2020-Q3,quarter,VNM,1.557723e+13,-1.407169e+10,1.556316e+13,-8.296415e+12,7.266743e+12,3.585911e+11,-1.204701e+11,-3.825722e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.701552e+09
2020-Q4,quarter,VNM,1.442990e+13,-5.106000e+09,1.442479e+13,-7.766621e+12,6.658174e+12,6.022703e+11,-6.499612e+10,-2.585785e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.504625e+10
2021-Q1,quarter,VNM,1.324072e+13,-5.044496e+10,1.319027e+13,-7.435390e+12,5.754880e+12,2.848399e+11,-6.424291e+09,-1.290599e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-8.845432e+09
2021-Q2,quarter,VNM,1.572879e+13,-1.298028e+10,1.571581e+13,-8.861449e+12,6.854357e+12,2.927671e+11,-4.213367e+10,-2.807226e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.958236e+10
2021-Q3,quarter,VNM,1.620827e+13,-1.421840e+10,1.619405e+13,-9.250305e+12,6.943747e+12,3.142420e+11,-6.354906e+10,-2.437457e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.454870e+10
2021-Q4,quarter,VNM,1.583430e+13,-1.526565e+10,1.581904e+13,-9.093720e+12,6.725317e+12,3.228348e+11,-9.023121e+10,-2.344628e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.116534e+10
2022-Q1,quarter,VNM,1.394047e+13,-6.264683e+10,1.387783e+13,-8.253022e+12,5.624804e+12,3.202834e+11,-1.324766e+11,-2.616860e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.523630e+10
2022-Q2,quarter,VNM,1.495941e+13,-2.913570e+10,1.493028e+13,-8.853615e+12,6.076660e+12,3.418149e+11,-1.350246e+11,-3.670164e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.062562e+10
2022-Q3,quarter,VNM,1.609411e+13,-1.462196e+10,1.607949e+13,-9.729312e+12,6.350180e+12,3.386154e+11,-1.427932e+11,-4.994230e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.691288e+09
2022-Q4,quarter,VNM,1.508073e+13,-1.207853e+10,1.506865e+13,-9.223066e+12,5.845588e+12,3.791908e+11,-2.072428e+11,-5.322655e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.556583e+09
2023-Q1,quarter,VNM,1.395402e+13,-3.562771e+10,1.391839e+13,-8.520366e+12,5.398026e+12,4.197051e+11,-1.582408e+11,-8.229192e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.376024e+10
2023-Q2,quarter,VNM,1.521294e+13,-1.811445e+10,1.519482e+13,-9.044633e+12,6.150192e+12,3.839639e+11,-1.159577e+11,-9.597064e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.120100e+10
2023-Q3,quarter,VNM,1.568149e+13,-4.450697e+10,1.563699e+13,-9.082087e+12,6.554901e+12,4.838299e+11,-1.101384e+11,-7.960068e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.763260e+10
2023-Q4,quarter,VNM,1.563046e+13,-1.174792e+10,1.561871e+13,-9.177098e+12,6.441613e+12,4.288687e+11,-1.187858e+11,-9.623160e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.803746e+10
2024-Q1,quarter,VNM,1.412489e+13,-1.247894e+10,1.411241e+13,-8.200890e+12,5.911521e+12,3.873688e+11,-1.024899e+11,-8.639543e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.032620e+10
2024-Q2,quarter,VNM,1.666524e+13,-9.453071e+09,1.665579e+13,-9.588269e+12,7.067519e+12,3.731837e+11,-8.767906e+10,-6.429445e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.339878e+09
2024-Q3,quarter,VNM,1.554871e+13,-1.137007e+10,1.553734e+13,-9.135892e+12,6.401445e+12,4.304765e+11,-9.796243e+10,-6.262483e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.059420e+09
2024-Q4,quarter,VNM,1.548505e+13,-7.978311e+09,1.547707e+13,-9.267382e+12,6.209691e+12,3.946319e+11,-1.401072e+11,-6.610986e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.339601e+10
2025-Q1,quarter,VNM,1.296540e+13,-3.089952e+10,1.293451e+13,-7.724023e+12,5.210482e+12,3.663372e+11,-4.176537e+10,-7.515521e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.618905e+10
2025-Q2,quarter,VNM,1.674461e+13,-2.001220e+10,1.672460e+13,-9.702920e+12,7.021678e+12,3.763331e+11,-1.095476e+11,-8.520433e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.760327e+09
2025-Q3,quarter,VNM,1.696808e+13,-1.485256e+10,1.695323e+13,-9.865935e+12,7.087297e+12,3.958404e+11,-9.135449e+10,-7.546463e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.944919e+11
2025-Q4,quarter,VNM,1.704542e+13,-1.186897e+10,1.703355e+13,-1.014354e+13,6.890017e+12,3.583412e+11,-1.075666e+11,-8.998018e+10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.398447e+10

### `ratio()`
Retrieve financial ratios.

In [27]:
df_ratio = instance.ratio(period='quarter')
display(df_ratio)

,report_period,Ratio TTM Id,Ratio Type,Outstanding Shares (mil),Market Cap,Dividend Yield (%),P/E,P/B,P/S,Price/Cash Flow,...,EBITDA,ROIC,Cash Cycle,Fixed Asset Turnover,Financial Leverage,CIR,CAR,Equity,CASA Ratio,Ratio Year Id
period,,,,,,,,,,,,,,,,,,,,,
2018-Q1,quarter,2699032,RATIO_TTM,1451246749,2.445351e+14,0.000000,24.304100,9.475260,4.784279,33.965322,...,1.245018e+13,0.393875,135.377248,5.439786,0.343760,0.0,None,None,None,NaN
2018-Q2,quarter,2713643,RATIO_TTM,1741426616,2.042693e+14,0.017050,20.831284,7.842925,3.968982,29.933722,...,1.229982e+13,0.379493,139.412965,5.077620,0.363561,0.0,None,None,None,NaN
2018-Q3,quarter,2715826,RATIO_TTM,1741407855,2.359608e+14,0.022140,24.396352,9.268315,4.545696,36.040876,...,1.216855e+13,0.390989,140.679632,4.730624,0.311220,0.0,None,None,None,NaN
2018-Q4,quarter,2717446,RATIO_TTM,1741407855,2.260347e+14,0.023112,22.104709,8.767447,4.300349,27.772044,...,1.283880e+13,0.407016,146.339646,4.384792,0.422313,0.0,None,None,None,NaN
2019-Q1,quarter,2722819,RATIO_TTM,1741378252,2.150602e+14,0.000000,20.846417,7.590057,4.010017,24.150228,...,1.320432e+13,0.367494,144.926423,4.362671,0.324377,0.0,None,None,None,NaN
2019-Q2,quarter,2725720,RATIO_TTM,1741377694,2.335187e+14,0.014914,22.136953,8.240015,4.282608,24.329675,...,1.363637e+13,0.365465,144.494663,4.252621,0.388915,0.0,None,None,None,NaN
2019-Q3,quarter,2730874,RATIO_TTM,1741377694,2.030446e+14,0.025729,19.013615,7.448421,3.686167,18.794592,...,1.403746e+13,0.378441,147.666025,4.151453,0.440408,0.0,None,None,None,NaN
2019-Q4,quarter,2735058,RATIO_TTM,1741377694,1.723964e+14,0.030303,16.295646,6.268035,3.061118,15.112022,...,1.413053e+13,0.346036,140.972633,3.985869,0.503464,0.0,None,None,None,NaN
2020-Q1,quarter,2748786,RATIO_TTM,1741377694,1.913774e+14,0.000000,18.131038,6.377020,3.340974,16.094615,...,1.421965e+13,0.316450,141.134697,4.084233,0.428786,0.0,None,None,None,NaN
2020-Q2,quarter,2751865,RATIO_TTM,2089645346,2.256817e+14,0.018519,21.036192,7.488879,3.879146,19.626638,...,1.431254e+13,0.315106,137.687758,4.067994,0.532862,0.0,None,None,None,NaN
2020-Q3,quarter,2754414,RATIO_TTM,2089645346,2.148155e+14,0.029183,19.326275,7.319848,3.613354,18.200805,...,1.478002e+13,0.329415,134.955850,4.117544,0.590219,0.0,None,None,None,NaN
2020-Q4,quarter,2758236,RATIO_TTM,2089955445,1.954108e+14,0.032086,17.606266,6.243720,3.276710,19.195244,...,1.447184e+13,0.298144,125.197347,4.148994,0.439424,0.0,None,None,None,NaN
2021-Q1,quarter,2761528,RATIO_TTM,2089955445,1.803632e+14,0.000000,16.529231,5.756513,3.074016,19.003947,...,1.400540e+13,0.273264,138.820404,4.213113,0.503100,0.0,None,None,None,NaN
2021-Q3,quarter,2767374,RATIO_TTM,2089955445,1.743023e+14,0.034772,16.562047,5.605226,2.928224,17.882728,...,1.360156e+13,0.266767,145.610787,4.432486,0.537059,0.0,None,None,None,NaN
2021-Q4,quarter,2765570,RATIO_TTM,2089955445,1.550747e+14,0.039084,14.719342,4.687404,2.545581,16.436765,...,1.360156e+13,0.266767,145.610787,4.432486,0.537059,0.0,None,None,None,NaN
2022-Q1,quarter,2770326,RATIO_TTM,2089955445,1.515218e+14,0.020690,14.818692,4.705944,2.459501,18.058759,...,1.388166e+13,0.259563,133.560402,4.587216,0.487649,0.0,None,None,None,NaN
2022-Q2,quarter,2777320,RATIO_TTM,2089955445,1.542387e+14,0.020325,16.281899,4.518364,2.535937,18.531395,...,1.281349e+13,0.229258,148.606806,4.818966,0.462287,0.0,None,None,None,NaN
2022-Q3,quarter,2779577,RATIO_TTM,2089955445,1.684504e+14,0.035980,19.043698,5.409208,2.774827,19.810716,...,1.224068e+13,0.233813,144.544548,4.913933,0.512803,0.0,None,None,None,NaN
2022-Q4,quarter,2783274,RATIO_TTM,2089955445,1.521488e+14,0.039835,17.860993,5.097273,2.537663,17.231215,...,1.184862e+13,0.258364,141.606332,4.872549,0.477386,0.0,None,None,None,NaN
2023-Q1,quarter,2795705,RATIO_TTM,2089955445,1.536117e+14,0.000000,18.941984,4.876317,2.560331,17.428489,...,1.128807e+13,0.221914,141.014461,4.994248,0.427542,0.0,None,None,None,NaN
2023-Q2,quarter,2799032,RATIO_TTM,2089955445,1.577916e+14,0.019868,19.183335,4.714668,2.618454,16.902510,...,1.142062e+13,0.216801,137.825226,5.063150,0.390309,0.0,None,None,None,NaN
2023-Q3,quarter,2801458,RATIO_TTM,2089955445,1.404450e+14,0.043155,16.686025,4.581387,2.347838,15.537064,...,1.144409e+13,0.228108,140.123209,5.018906,0.616544,0.0,None,None,None,NaN
2023-Q4,quarter,2804454,RATIO_TTM,2089955445,1.394000e+14,0.043478,15.709148,4.397919,2.309136,17.673709,...,1.182561e+13,0.224714,138.823695,4.909467,0.503847,0.0,None,None,None,NaN
2024-Q1,quarter,2808344,RATIO_TTM,2089955445,1.385640e+14,0.000000,15.042104,4.349950,2.287935,15.989050,...,1.239970e+13,0.237123,138.424856,4.939901,0.440127,0.0,None,None,None,NaN
2024-Q2,quarter,2810971,RATIO_TTM,2089955445,1.404450e+14,0.022321,14.503672,4.089108,2.264369,16.230433,...,1.292471e+13,0.229757,137.454881,5.010608,0.413604,0.0,None,None,None,NaN
2024-Q3,quarter,2814519,RATIO_TTM,2089955445,1.287413e+14,0.032468,13.417990,4.103819,2.079012,14.505093,...,1.290004e+13,0.241324,138.201987,5.023053,0.636495,0.0,None,None,None,NaN
2024-Q4,quarter,2817173,RATIO_TTM,2089955445,1.176645e+14,0.035524,12.527747,3.645254,1.904492,12.147971,...,1.249971e+13,0.228934,136.004773,4.895569,0.521768,0.0,None,None,None,NaN
2025-Q1,quarter,2821262,RATIO_TTM,2089955445,1.260243e+14,0.000000,14.376284,3.739904,2.079448,14.563100,...,1.169634e+13,0.200558,139.030262,4.946294,0.462258,0.0,None,None,None,NaN
2025-Q2,quarter,2823440,RATIO_TTM,2089955445,1.327122e+14,0.039370,15.485241,4.176707,2.187316,14.375058,...,1.150532e+13,0.206816,141.242119,4.902983,0.549096,0.0,None,None,None,NaN
2025-Q3,quarter,2826916,RATIO_TTM,2089955445,1.414900e+14,0.036928,16.275408,4.149514,2.278810,17.202811,...,1.188697e+13,0.212213,138.850451,4.917198,0.467028,0.0,None,None,None,NaN
2025-Q4,quarter,2828360,RATIO_TTM,2089955445,1.291592e+14,0.040453,13.725449,4.209146,2.029342,14.900462,...,1.277996e+13,0.242690,134.234570,5.051365,0.546047,0.0,None,None,None,NaN

### `note()`
Retrieve financial statement notes (thuyết minh báo cáo tài chính) if source is 'vci'.

In [26]:
df_note = instance.note(period='quarter')
display(df_note)

,report_period,ticker,Cash and cash equivalents,Cash on hand,Cash in banks,Cash in transit,Cash equivalents,Short-term investments,Short-term securities investments,Other short-term investments,...,Short-term,Long-term,noc159,noc160,noc161,noc162,noc163,noc164,noc165,noc166
period,,,,,,,,,,,,,,,,,,,,,
2018-Q1,quarter,VNM,5.633927e+11,2.296740e+09,5.110960e+11,0.000000e+00,5.000000e+10,9.219519e+12,7.642963e+08,0.0,...,9.219433e+12,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-Q2,quarter,VNM,1.343435e+12,1.891732e+09,8.065400e+11,3.542286e+06,5.350000e+11,9.210771e+12,4.431433e+11,0.0,...,8.768311e+12,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2018-Q3,quarter,VNM,6.307847e+11,1.954583e+10,5.260328e+11,2.060769e+08,8.500000e+10,7.872300e+12,4.431613e+11,0.0,...,7.329833e+12,1.000000e+11,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2018-Q4,quarter,VNM,1.522610e+12,1.853589e+09,9.889965e+11,8.176011e+10,4.500000e+11,8.673927e+12,4.431543e+11,0.0,...,8.231378e+12,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-Q1,quarter,VNM,1.209154e+12,1.323867e+09,1.027831e+12,0.000000e+00,1.800000e+11,9.666847e+12,4.431550e+11,0.0,...,9.224298e+12,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2019-Q2,quarter,VNM,1.676491e+12,2.515086e+09,8.239762e+11,0.000000e+00,8.500000e+11,9.306531e+12,4.431579e+11,0.0,...,8.863981e+12,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2019-Q3,quarter,VNM,1.043474e+12,1.749186e+09,9.861245e+11,0.000000e+00,5.560000e+10,1.023829e+13,4.431545e+11,0.0,...,9.795737e+12,0.000000e+00,8.148127e+10,1.473205e+11,0.000000e+00,-6.583918e+10,1.890766e+10,5.707225e+10,3.055015e+09,-4.121960e+10
2019-Q4,quarter,VNM,2.665195e+12,2.104241e+09,2.376480e+12,0.000000e+00,2.866109e+11,1.243574e+13,1.153041e+09,0.0,...,1.243543e+13,0.000000e+00,8.148127e+10,1.473205e+11,0.000000e+00,-6.583918e+10,1.946315e+10,5.707225e+10,3.610507e+09,-4.121960e+10
2020-Q1,quarter,VNM,1.379712e+12,2.164384e+09,1.026247e+12,0.000000e+00,3.513000e+11,1.437029e+13,1.148118e+09,0.0,...,1.436999e+13,0.000000e+00,8.148127e+10,8.148127e+10,0.000000e+00,0.000000e+00,2.001566e+10,1.946315e+10,5.525087e+08,0.000000e+00
2020-Q2,quarter,VNM,2.176667e+12,1.668908e+09,2.042998e+12,0.000000e+00,1.320000e+11,1.636306e+13,1.129064e+09,0.0,...,1.636277e+13,0.000000e+00,8.148127e+10,8.148127e+10,0.000000e+00,0.000000e+00,2.056817e+10,1.946315e+10,1.105017e+09,0.000000e+00
2020-Q3,quarter,VNM,2.335881e+12,1.469261e+09,9.944272e+11,0.000000e+00,1.339985e+12,1.787200e+13,1.128087e+09,0.0,...,1.787171e+13,0.000000e+00,8.148127e+10,8.148127e+10,0.000000e+00,0.000000e+00,2.107346e+10,1.946315e+10,1.610303e+09,0.000000e+00
2020-Q4,quarter,VNM,2.111243e+12,1.347052e+09,8.625062e+11,0.000000e+00,1.247390e+12,1.731368e+13,1.124179e+09,0.0,...,1.731349e+13,0.000000e+00,8.148127e+10,8.148127e+10,0.000000e+00,0.000000e+00,2.148430e+10,1.946315e+10,2.021143e+09,0.000000e+00
2021-Q1,quarter,VNM,1.197957e+12,1.866938e+09,8.681141e+11,0.000000e+00,3.279757e+11,1.954279e+13,1.123202e+09,0.0,...,1.954261e+13,0.000000e+00,9.882268e+10,8.148127e+10,1.734141e+10,0.000000e+00,3.577175e+10,2.148430e+10,1.428746e+10,0.000000e+00
2021-Q2,quarter,VNM,1.663036e+12,3.306947e+09,1.258170e+12,0.000000e+00,4.015591e+11,1.997122e+13,1.129553e+09,0.0,...,1.997103e+13,0.000000e+00,9.882268e+10,8.148127e+10,1.734141e+10,0.000000e+00,3.681562e+10,2.148430e+10,1.533132e+10,0.000000e+00
2021-Q3,quarter,VNM,2.051857e+12,2.255276e+09,1.430675e+12,0.000000e+00,6.189272e+11,1.975314e+13,1.116850e+09,0.0,...,1.975296e+13,0.000000e+00,9.882268e+10,8.148127e+10,1.734141e+10,0.000000e+00,3.785949e+10,2.148430e+10,1.637519e+10,0.000000e+00
2021-Q4,quarter,VNM,2.348552e+12,1.485618e+09,1.185865e+12,0.000000e+00,1.161202e+12,2.102574e+13,1.119782e+09,0.0,...,2.102528e+13,0.000000e+00,9.882268e+10,8.148127e+10,1.734141e+10,0.000000e+00,3.877279e+10,2.148430e+10,1.728849e+10,0.000000e+00
2022-Q1,quarter,VNM,1.680858e+12,1.887192e+09,9.050876e+11,0.000000e+00,7.738834e+11,1.983283e+13,1.122713e+09,0.0,...,1.983237e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,3.941273e+10,3.877279e+10,6.399488e+08,0.000000e+00
2022-Q2,quarter,VNM,4.507497e+12,1.130698e+09,1.199288e+12,0.000000e+00,3.307079e+12,1.897616e+13,1.143966e+09,0.0,...,1.897570e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.004658e+10,3.877279e+10,1.273797e+09,0.000000e+00
2022-Q3,quarter,VNM,2.867858e+12,1.285831e+09,1.903027e+12,0.000000e+00,9.635450e+11,1.953356e+13,1.173035e+09,0.0,...,1.953309e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.068043e+10,3.877279e+10,1.907646e+09,0.000000e+00
2022-Q4,quarter,VNM,2.299944e+12,1.715151e+09,1.325714e+12,0.000000e+00,9.725140e+11,1.741406e+13,1.159355e+09,0.0,...,1.741359e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.122887e+10,3.877279e+10,2.456086e+09,0.000000e+00
2023-Q1,quarter,VNM,2.011203e+12,9.992387e+08,9.240927e+11,0.000000e+00,1.086111e+12,1.680133e+13,1.154470e+09,0.0,...,1.680086e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.173461e+10,4.122887e+10,5.057364e+08,0.000000e+00
2023-Q2,quarter,VNM,1.582507e+12,1.268604e+09,7.905117e+11,0.000000e+00,7.907264e+11,1.908300e+13,1.160332e+09,0.0,...,1.908253e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.224034e+10,4.122887e+10,1.011473e+09,0.000000e+00
2023-Q3,quarter,VNM,6.875568e+12,1.123143e+09,4.243242e+12,0.000000e+00,2.631203e+12,1.901212e+13,1.195020e+09,0.0,...,1.901164e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.273443e+10,4.122887e+10,1.505563e+09,0.000000e+00
2023-Q4,quarter,VNM,2.912027e+12,1.545333e+09,1.023942e+12,0.000000e+00,1.886540e+12,2.013724e+13,1.193066e+09,0.0,...,2.013687e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.322852e+10,4.122887e+10,1.999653e+09,0.000000e+00
2024-Q1,quarter,VNM,1.788255e+12,9.434995e+08,7.892417e+11,0.000000e+00,9.980697e+11,2.026813e+13,1.219937e+09,0.0,...,2.026775e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.372261e+10,4.322852e+10,4.940903e+08,0.000000e+00
2024-Q2,quarter,VNM,1.198563e+12,1.349006e+09,1.017214e+12,0.000000e+00,1.800000e+11,2.303088e+13,1.244511e+09,0.0,...,2.303051e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.421671e+10,4.322852e+10,9.881806e+08,0.000000e+00
2024-Q3,quarter,VNM,2.616235e+12,1.101513e+09,1.420133e+12,0.000000e+00,1.195000e+12,2.598284e+13,1.208700e+09,0.0,...,2.598249e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.471080e+10,4.322852e+10,1.482271e+09,0.000000e+00
2024-Q4,quarter,VNM,2.225944e+12,9.452050e+08,1.876999e+12,0.000000e+00,3.480000e+11,2.326009e+13,1.248322e+09,0.0,...,2.325976e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.520489e+10,4.322852e+10,1.976361e+09,0.000000e+00
2025-Q1,quarter,VNM,2.538024e+12,9.247200e+08,1.227780e+12,0.000000e+00,1.309320e+12,2.317082e+13,1.257556e+09,0.0,...,2.317049e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.569898e+10,4.520489e+10,4.940903e+08,0.000000e+00
2025-Q2,quarter,VNM,2.498443e+12,1.228216e+09,2.136215e+12,0.000000e+00,3.610000e+11,2.224942e+13,1.284915e+09,0.0,...,2.224919e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.619307e+10,4.520489e+10,9.881806e+08,0.000000e+00
2025-Q3,quarter,VNM,5.154466e+12,1.094133e+09,1.426372e+12,0.000000e+00,3.727000e+12,2.113395e+13,1.292048e+09,0.0,...,2.113371e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.663166e+10,4.520489e+10,1.426770e+09,0.000000e+00
2025-Q4,quarter,VNM,1.794880e+12,1.133259e+09,1.629746e+12,0.000000e+00,1.640000e+11,2.135486e+13,1.288677e+09,0.0,...,2.135442e+13,0.000000e+00,9.882268e+10,9.882268e+10,0.000000e+00,0.000000e+00,4.704250e+10,4.520489e+10,1.837610e+09,0.000000e+00