# API Adapter - TopStock
Demo tự động các hàm trong class `TopStock`.

In [2]:
from vnstock_data.api.insight import TopStock

# Khởi tạo instance
instance = TopStock(source='VND', symbol='VNM')

### `deal()`
Top 10 by block trade volume in the given index.

In [3]:
df_deal = instance.deal()
display(df_deal)

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,SIP,VNINDEX,60.80,2026-04-10 15:59,-0.60,-0.977199,1.163815e+10,293070.0,65.103900,3.607175e+05,140.275978,47.405518,855000.0,4.146120e+09,171000.00
1,SSB,VNINDEX,17.15,2026-04-10 15:59,0.00,0.000000,4.043406e+10,1935965.0,122.414403,8.123662e+06,43.415521,8.683104,3526930.0,1.209737e+02,705386.00
2,BKG,VNINDEX,2.59,2026-04-10 15:59,0.01,0.387597,9.127040e+08,77260.0,456.769350,6.075500e+05,21.397416,269.936631,8200000.0,3.914420e+09,1640000.00
3,SCR,VNINDEX,6.25,2026-04-10 15:59,0.00,0.000000,1.053594e+10,2072125.0,81.148579,2.277134e+06,14.749070,32.449446,3694587.1,3.963291e+09,738917.42
4,FRT,VNINDEX,152.00,2026-04-10 15:59,2.00,1.333333,6.239099e+10,354915.0,116.140484,5.095452e+05,14.047820,10.486017,267155.0,5.867250e+09,53431.00
5,HDB,VNINDEX,26.15,2026-04-10 15:59,0.10,0.383877,2.854425e+11,13603645.0,79.478699,2.029558e+07,5.917544,23.533498,23881301.0,1.161123e+11,4776260.20
6,BSI,VNINDEX,37.00,2026-04-10 15:59,-0.20,-0.537634,1.175452e+10,391530.0,80.300360,4.146300e+05,5.305935,11.673058,242000.0,1.568600e+09,48400.00
7,KDC,VNINDEX,48.80,2026-04-10 15:59,0.00,0.000000,9.743085e+09,198160.0,100.726686,5.846345e+05,4.276176,28.222761,825000.0,7.799600e+09,165000.00
8,VIX,VNINDEX,18.05,2026-04-10 15:59,0.05,0.277778,7.532346e+11,35638695.0,115.995830,4.120415e+07,4.188796,12.299022,25338535.8,7.808149e+10,5067707.16
9,VPB,VNINDEX,27.30,2026-04-10 15:59,0.20,0.738007,3.981577e+11,15977185.0,90.432075,1.883439e+07,3.855554,19.215989,18096070.0,9.440515e+10,3619214.00

### `foreign_buy()`
Top 10 net foreign buys on the given date.

In [4]:
df_foreign_buy = instance.foreign_buy()
display(df_foreign_buy)

  symbol        date     net_value
0    TCB  2026-04-10  2.179768e+11
1    HPG  2026-04-10  1.796444e+11
2    MBB  2026-04-10  1.005341e+11
3    VNM  2026-04-10  9.388876e+10
4    MSN  2026-04-10  7.162151e+10
5    BSR  2026-04-10  7.095849e+10
6    DXG  2026-04-10  5.452718e+10
7    VCB  2026-04-10  5.211277e+10
8    VCI  2026-04-10  5.073029e+10
9    NVL  2026-04-10  5.062585e+10

### `foreign_sell()`
Top 10 net foreign sells on the given date.

In [5]:
df_foreign_sell = instance.foreign_sell()
display(df_foreign_sell)

  symbol        date     net_value
0    BID  2026-04-10 -6.847928e+10
1    VHM  2026-04-10 -4.371136e+10
2    FRT  2026-04-10 -3.735763e+10
3    VPB  2026-04-10 -3.394367e+10
4    KDH  2026-04-10 -3.345910e+10
5    MWG  2026-04-10 -3.074975e+10
6    GAS  2026-04-10 -2.680528e+10
7    ACB  2026-04-10 -2.355309e+10
8    FPT  2026-04-10 -1.402052e+10
9    VIX  2026-04-10 -1.398705e+10

### `gainer()`
Top 10 gainers in the given index.

In [6]:
df_gainer = instance.gainer()
display(df_gainer)

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,BSR,VNINDEX,26.75,2026-04-10 15:59,1.75,7.000000,5.280704e+11,17905615.0,112.255848,17935256.00,0.034680,0.145657,130620.0,6.493680e+08,26124.00
1,VVS,VNINDEX,105.90,2026-04-10 15:59,6.90,6.969697,1.385209e+10,263025.0,49.957228,263025.00,0.000000,0.000000,0.0,0.000000e+00,0.00
2,CCC,VNINDEX,8.07,2026-04-10 15:59,0.52,6.887417,3.599870e+08,10465.0,437.649307,10465.00,0.000000,0.000000,0.0,0.000000e+00,0.00
3,SMC,VNINDEX,13.35,2026-04-10 15:59,0.85,6.800000,1.425722e+10,403075.0,270.148235,1027584.70,0.000000,0.000000,0.0,0.000000e+00,0.00
4,TDG,VNINDEX,2.74,2026-04-10 15:59,0.14,5.384615,4.826940e+08,67595.0,266.143946,67595.00,0.000000,0.000000,0.0,0.000000e+00,0.00
5,MSB,VNINDEX,12.75,2026-04-10 15:59,0.65,5.371901,4.402985e+11,7574900.0,458.024528,12767514.98,3.114746,57.699992,36834275.6,8.439047e+10,7366855.12
6,PVD,VNINDEX,33.90,2026-04-10 15:59,1.50,4.629630,1.725323e+11,5337985.0,96.720017,6340285.00,3.400478,14.282008,4527600.0,2.957212e+10,905520.00
7,TCB,VNINDEX,32.25,2026-04-10 15:59,1.35,4.368932,9.864523e+11,12023260.0,255.259389,15402078.00,0.324632,11.033966,8497300.0,5.068239e+10,1699460.00
8,BFC,VNINDEX,57.90,2026-04-10 15:59,2.40,4.324324,1.406592e+10,173155.0,140.625451,173155.00,0.000000,0.000000,0.0,0.000000e+00,0.00
9,PLX,VNINDEX,41.15,2026-04-10 15:59,1.65,4.177215,2.340260e+11,4933660.0,115.476137,4933885.00,0.000000,0.000000,0.0,0.000000e+00,0.00

### `loser()`
Top 10 losers in the given index.

In [8]:
df_loser = instance.loser()
display(df_loser)

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,DCL,VNINDEX,41.85,2026-04-10 15:59,-3.15,-7.000000,4.093038e+10,645810.0,148.635047,654310.00,0.000000,3.056655,100000.0,9.830000e+08,20000.0
1,BVH,VNINDEX,76.40,2026-04-10 15:59,-3.40,-4.260652,1.227322e+11,757820.0,210.933995,757820.00,0.000000,0.000000,0.0,0.000000e+00,0.0
2,C47,VNINDEX,10.40,2026-04-10 15:59,-0.45,-4.147465,1.369850e+08,78590.0,16.414302,103340.00,0.000000,0.000000,0.0,0.000000e+00,0.0
3,CRE,VNINDEX,7.70,2026-04-10 15:59,-0.25,-3.144654,1.074888e+09,254065.0,54.238089,254065.00,0.000000,0.000000,0.0,0.000000e+00,0.0
4,VPG,VNINDEX,3.81,2026-04-10 15:59,-0.12,-3.053435,2.137807e+09,242865.0,230.786651,242865.00,0.000000,0.000000,0.0,0.000000e+00,0.0
5,DSC,VNINDEX,13.10,2026-04-10 15:59,-0.40,-2.962963,3.928500e+08,25575.0,116.129032,26775.00,0.000000,0.000000,0.0,0.000000e+00,0.0
6,CVT,VNINDEX,24.95,2026-04-10 15:59,-0.75,-2.918288,3.104050e+08,11180.0,111.806798,11180.00,0.000000,0.000000,0.0,0.000000e+00,0.0
7,DQC,VNINDEX,9.00,2026-04-10 15:59,-0.25,-2.702703,9.148800e+07,10400.0,98.076923,10400.00,0.000000,0.000000,0.0,0.000000e+00,0.0
8,NBB,VNINDEX,18.00,2026-04-10 15:59,-0.40,-2.173913,3.277050e+08,42450.0,42.873969,50950.00,0.000000,0.000000,0.0,0.000000e+00,0.0
9,PET,VNINDEX,48.50,2026-04-10 15:59,-1.05,-2.119072,3.333596e+10,1477610.0,46.385717,1875792.05,1.967169,11.801948,1106900.0,1.060905e+10,221380.0

### `value()`
Top 10 by trading value in the given index.

In [9]:
df_value = instance.value()
display(df_value)

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,SHB,VNINDEX,15.40,2026-04-10 15:59,-0.10,-0.645161,1.621547e+12,69944440.0,150.964680,73827935.85,0.365851,8.381462,30939301.0,9.156763e+10,6187860.20
1,HPG,VNINDEX,28.00,2026-04-10 15:59,-0.25,-0.884956,1.004138e+12,33529855.0,105.796461,36357499.15,0.141649,23.176788,42132503.0,2.273685e+11,8426500.60
2,TCB,VNINDEX,32.25,2026-04-10 15:59,1.35,4.368932,9.864523e+11,12023260.0,255.259389,15402078.00,0.324632,11.033966,8497300.0,5.068239e+10,1699460.00
3,MBB,VNINDEX,26.70,2026-04-10 15:59,0.20,0.754717,8.163455e+11,16809280.0,180.419982,21030699.45,0.213973,4.088309,4299000.0,2.245779e+10,859800.00
4,VIX,VNINDEX,18.05,2026-04-10 15:59,0.05,0.277778,7.532346e+11,35638695.0,115.995830,41204146.24,4.188796,12.299022,25338535.8,7.808149e+10,5067707.16
5,EIB,VNINDEX,23.10,2026-04-10 15:59,0.50,2.212389,7.038401e+11,10463860.0,287.015499,16313139.80,0.000000,9.489283,7740000.0,3.498884e+10,1548000.00
6,STB,VNINDEX,66.90,2026-04-10 15:59,0.60,0.904977,6.827650e+11,8760370.0,115.848988,11877825.00,0.227314,39.700534,23577800.0,2.856008e+11,4715560.00
7,SSI,VNINDEX,28.60,2026-04-10 15:59,-0.15,-0.521739,6.799293e+11,32799695.0,71.808899,33020420.60,0.006057,0.516046,852003.0,5.055116e+09,170400.60
8,BSR,VNINDEX,26.75,2026-04-10 15:59,1.75,7.000000,5.280704e+11,17905615.0,112.255848,17935256.00,0.034680,0.145657,130620.0,6.493680e+08,26124.00
9,FPT,VNINDEX,77.70,2026-04-10 15:59,-0.60,-0.766284,4.752204e+11,8584620.0,71.054980,9278810.40,0.000000,5.456012,2531265.0,3.955697e+10,506253.00

### `volume()`
Top 10 by abnormal volume in the given index.

In [10]:
df_volume = instance.volume()
display(df_volume)

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,HSL,VNINDEX,5.00,2026-04-10 15:59,0.09,1.832994,7.567704e+09,194645.0,763.081507,197145.00,0.000000,0.000000,0.0,0.000000e+00,0.00
1,QCG,VNINDEX,14.75,2026-04-10 15:59,0.35,2.430556,3.074446e+10,420590.0,475.950451,420590.00,0.000000,0.000000,0.0,0.000000e+00,0.00
2,CDC,VNINDEX,23.40,2026-04-10 15:59,0.00,0.000000,3.624154e+10,335140.0,463.507788,381885.00,0.000000,18.853843,360000.0,1.584000e+09,72000.00
3,THG,VNINDEX,45.30,2026-04-10 15:59,1.05,2.372881,5.807265e+09,27950.0,462.969589,27950.00,0.000000,0.000000,0.0,0.000000e+00,0.00
4,MSB,VNINDEX,12.75,2026-04-10 15:59,0.65,5.371901,4.402985e+11,7574900.0,458.024528,12767514.98,3.114746,57.699992,36834275.6,8.439047e+10,7366855.12
5,BKG,VNINDEX,2.59,2026-04-10 15:59,0.01,0.387597,9.127040e+08,77260.0,456.769350,607550.00,21.397416,269.936631,8200000.0,3.914420e+09,1640000.00
6,CCC,VNINDEX,8.07,2026-04-10 15:59,0.52,6.887417,3.599870e+08,10465.0,437.649307,10465.00,0.000000,0.000000,0.0,0.000000e+00,0.00
7,CNG,VNINDEX,25.20,2026-04-10 15:59,0.55,2.231237,1.909750e+09,20340.0,370.698132,20340.00,0.000000,0.000000,0.0,0.000000e+00,0.00
8,VNS,VNINDEX,8.01,2026-04-10 15:59,-0.12,-1.476015,7.712010e+08,25955.0,370.641495,45955.00,0.000000,174.083342,400000.0,6.400000e+08,80000.00
9,GSP,VNINDEX,11.30,2026-04-10 15:59,0.05,0.444444,4.623480e+09,119295.0,347.290331,119295.00,0.000000,0.000000,0.0,0.000000e+00,0.00