# API Adapter - Macro
Demo tự động các hàm trong class `Macro`.

In [5]:
from vnstock_data.api.macro import Macro

# Khởi tạo instance
instance = Macro()

### `cpi()`
Fetch CPI series.

In [6]:
df_cpi = instance.cpi()
display(df_cpi)

,last_updated,name,value,unit,source
report_time,,,,,
2016-04-30,2016-04-25,Lương thực,1.11,%,Tổng cục thống kê
2016-04-30,2016-04-25,Chỉ số giá tiêu dùng,0.33,%,Tổng cục thống kê
2016-04-30,2016-04-25,So sánh với cùng kỳ năm trước,1.89,%,Tổng cục thống kê
2016-04-30,2016-04-25,Đồ dùng và dịch vụ khác,0.10,%,Tổng cục thống kê
2016-04-30,2016-04-25,"Văn hóa, giải trí và du lịch",-0.01,%,Tổng cục thống kê
...,...,...,...,...,...
2025-08-31,2025-09-05,Ăn uống ngoài gia đình,0.20,%,Tổng cục thống kê
2025-08-31,2025-09-05,Thực phẩm,-0.18,%,Tổng cục thống kê
2025-08-31,2025-09-05,Lương thực,0.01,%,Tổng cục thống kê
2025-08-31,2025-09-05,Thiết bị và đồ dùng gia đình,0.11,%,Tổng cục thống kê
2025-08-31,2025-09-05,Chỉ số giá tiêu dùng,0.05,%,Tổng cục thống kê

### `exchange_rate()`
Fetch Exchange Rate series.

In [7]:
df_exchange_rate = instance.exchange_rate()
display(df_exchange_rate)

,last_updated,name,value,unit,source
report_time,,,,,
2017-02-01,2017-01-31,Tỷ giá trung tâm (từ 04/01/2016),22202.0,USD/VNĐ,None
2017-02-01,2017-01-31,Liên ngân hàng,NaN,USD/VNĐ,Ngân hàng Nhà nước Việt Nam
2018-02-01,2018-01-31,Tỷ giá trung tâm (từ 04/01/2016),22431.0,USD/VNĐ,None
2018-02-01,2018-01-31,Liên ngân hàng,NaN,USD/VNĐ,Ngân hàng Nhà nước Việt Nam
2019-02-01,2019-01-31,Liên ngân hàng,NaN,USD/VNĐ,Ngân hàng Nhà nước Việt Nam
...,...,...,...,...,...
2022-12-31,2022-12-30,Liên ngân hàng,NaN,USD/VNĐ,Ngân hàng Nhà nước Việt Nam
2024-12-31,2024-12-30,Liên ngân hàng,NaN,USD/VNĐ,Ngân hàng Nhà nước Việt Nam
2024-12-31,2024-12-30,Tỷ giá trung tâm (từ 04/01/2016),24335.0,USD/VNĐ,None
2025-12-31,2025-12-30,Liên ngân hàng,NaN,USD/VNĐ,Ngân hàng Nhà nước Việt Nam
2025-12-31,2025-12-30,Tỷ giá trung tâm (từ 04/01/2016),25121.0,USD/VNĐ,None

### `fdi()`
Fetch Foreign Direct Investment series.

In [8]:
df_fdi = instance.fdi()
display(df_fdi)

,last_updated,group_name,name,value,unit,source
report_time,,,,,,
2016-04-30,2016-08-17,Tổng FDI,Đăng ký,2.85,Tỷ USD,Cục Đầu tư nước ngoài
2016-04-30,2016-08-17,Tổng FDI,Giải ngân,1.15,Tỷ USD,Cục Đầu tư nước ngoài
2016-04-30,2016-08-17,Tổng FDI,Đăng ký,2.85,Tỷ USD,Cục Đầu tư nước ngoài
2016-04-30,2016-08-17,Tổng FDI,Giải ngân,1.15,Tỷ USD,Cục Đầu tư nước ngoài
2016-05-31,2016-08-17,Tổng FDI,Đăng ký,3.28,Tỷ USD,Cục Đầu tư nước ngoài
...,...,...,...,...,...,...
2026-01-31,2026-02-05,Tổng FDI,Giải ngân,1.68,Tỷ USD,Cục Đầu tư nước ngoài
2026-02-28,2026-03-05,Tổng FDI,Đăng ký,3.45,Tỷ USD,Cục Đầu tư nước ngoài
2026-02-28,2026-03-05,Tổng FDI,Giải ngân,1.53,Tỷ USD,Cục Đầu tư nước ngoài
2026-03-31,2026-04-05,Tổng FDI,Đăng ký,9.17,Tỷ USD,Cục Đầu tư nước ngoài
2026-03-31,2026-04-05,Tổng FDI,Giải ngân,2.20,Tỷ USD,Cục Đầu tư nước ngoài

### `gdp()`
Fetch GDP series.

In [9]:
df_gdp = instance.gdp()
display(df_gdp)

,last_updated,group_name,name,value,unit,source,report_type
report_time,,,,,,,
2016-03-01,2016-03-29,Cơ cấu GDP theo giá hiện tại,Công nghiệp,34.24,%,Tổng cục thống kê,Quý 1
2016-03-01,2016-03-29,Cơ cấu GDP theo giá hiện tại,Dịch vụ,43.61,%,Tổng cục thống kê,Quý 1
2016-03-01,2016-03-29,Cơ cấu GDP theo giá hiện tại,Nông nghiệp,11.44,%,Tổng cục thống kê,Quý 1
2016-03-01,2016-03-29,Giá trị GDP (2010),Công nghiệp,197759.00,Tỷ VNĐ,None,Quý 1
2016-03-01,2016-03-29,Giá trị GDP (2010),Dịch vụ,229578.00,Tỷ VNĐ,None,Quý 1
...,...,...,...,...,...,...,...
2025-09-01,2025-10-05,Tăng trưởng thực của GDP,Dịch vụ,8.56,%,Tổng cục thống kê,Quý 3
2025-09-30,2025-10-05,Tăng trưởng thực của GDP,Nông nghiệp,3.83,%,Tổng cục thống kê,9 tháng
2025-09-01,2025-10-05,Tăng trưởng thực của GDP,Nông nghiệp,3.74,%,Tổng cục thống kê,Quý 3
2025-09-30,2025-10-05,Tăng trưởng thực của GDP,Tổng GDP,7.85,%,Tổng cục thống kê,9 tháng
2025-09-01,2025-10-05,Tăng trưởng thực của GDP,Tổng GDP,8.23,%,Tổng cục thống kê,Quý 3

### `import_export()`
Fetch Import-Export series.

In [11]:
df_import_export = instance.import_export()
display(df_import_export)

,last_updated,name,value,unit,source
report_time,,,,,
2016-04-30,2016-04-27,Tổng trị giá Nhập khẩu,14000.00,Triệu USD,Tổng cục thống kê
2016-04-30,2016-04-27,Máy móc thiết bị,750.00,Triệu USD,Tổng cục thống kê
2016-04-30,2016-04-27,Điện tử máy tính,1300.00,Triệu USD,Tổng cục thống kê
2016-04-30,2016-04-27,Thức ăn gia súc,280.00,Triệu USD,Tổng cục thống kê
2016-04-30,2016-04-27,Café,271.00,Triệu USD,Tổng cục thống kê
...,...,...,...,...,...
2025-07-31,2025-08-06,"Điện tử, máy tính và linh kiện",13839.05,Triệu USD,Tổng cục thống kê
2025-07-31,2025-08-06,Tổng trị giá Xuất khẩu,42265.54,Triệu USD,Tổng cục thống kê
2025-07-31,2025-08-06,Tổng trị giá Nhập khẩu,39998.52,Triệu USD,Tổng cục thống kê
2025-07-31,2025-08-06,Thủy sản,971.58,Triệu USD,Tổng cục thống kê
2025-07-31,2025-08-06,Máy móc thiết bị,5309.44,Triệu USD,Tổng cục thống kê

### `industry_prod()`
Fetch Industrial Production series.

In [12]:
df_industry_prod = instance.industry_prod()
display(df_industry_prod)

,last_updated,group_name,name,value,unit,source
report_time,,,,,,
2016-04-30,2016-04-26,Tăng trưởng,Toàn ngành công nghiệp,-11.70,%,None
2016-04-30,2016-04-26,Tăng trưởng,"Cung cấp nước, hoạt động quản lý và xử lý rác ...",2.40,%,None
2016-04-30,2016-04-26,Tăng trưởng,Khai khoáng,-10.20,%,None
2016-04-30,2016-04-26,Tăng trưởng,"Công nghiệp chế biến, chế tạo",0.50,%,None
2016-04-30,2016-04-26,Tăng trưởng,Sản xuất và Phân phối điện,2.70,%,None
...,...,...,...,...,...,...
2025-07-31,2025-08-06,Tăng trưởng,Toàn ngành công nghiệp,0.52,%,None
2025-07-31,2025-08-06,Tăng trưởng,Khai khoáng,-2.05,%,None
2025-07-31,2025-08-06,Tăng trưởng,"Công nghiệp chế biến, chế tạo",0.32,%,None
2025-07-31,2025-08-06,Tăng trưởng,Sản xuất và Phân phối điện,3.36,%,None
2025-07-31,2025-08-06,Tăng trưởng,"Cung cấp nước, hoạt động quản lý và xử lý rác ...",-1.42,%,None

### `interest_rate()`
Fetch Interest Rate series.

In [13]:
df_interest_rate = instance.interest_rate()
display(df_interest_rate)

2026-04-10 23:12:49 - vnstock_data.core.utils.client - ERROR - API request failed: Expecting value: line 1 column 2 (char 1)

ConnectionError: API request failed: Expecting value: line 1 column 2 (char 1)

### `money_supply()`
Fetch Money Supply series.

In [14]:
df_money_supply = instance.money_supply()
display(df_money_supply)

,last_updated,name,value,unit,source
report_time,,,,,
2016-04-30,2016-09-14,Tăng trưởng tín dụng,4.06,%,Ngân hàng Nhà nước Việt Nam
2016-04-30,2016-09-14,Cung tiền M2,6326334.00,Tỷ VNĐ,Ngân hàng Nhà nước Việt Nam
2016-04-30,2016-09-14,Tăng trưởng Cung tiền M2,5.10,%,Ngân hàng Nhà nước Việt Nam
2016-04-30,2016-09-14,Tín dụng,4845059.00,Tỷ VNĐ,Ngân hàng Nhà nước Việt Nam
2016-05-31,2016-09-14,Tăng trưởng tín dụng,5.49,%,Ngân hàng Nhà nước Việt Nam
...,...,...,...,...,...
2025-12-31,2026-03-03,Cung tiền M2,NaN,Tỷ VNĐ,Ngân hàng Nhà nước Việt Nam
2026-01-31,2026-03-22,Tăng trưởng tín dụng,1.19,%,Ngân hàng Nhà nước Việt Nam
2026-01-31,2026-03-22,Tăng trưởng Cung tiền M2,NaN,%,Ngân hàng Nhà nước Việt Nam
2026-01-31,2026-03-22,Tín dụng,18815882.09,Tỷ VNĐ,Ngân hàng Nhà nước Việt Nam
2026-01-31,2026-03-22,Cung tiền M2,NaN,Tỷ VNĐ,Ngân hàng Nhà nước Việt Nam

### `population_labor()`
Fetch Population and Labor series.

In [15]:
df_population_labor = instance.population_labor()
display(df_population_labor)

,last_updated,name,value,unit,source
report_time,,,,,
2016,2017-01-03,Số lượng lao động,53.29,Triệu người,ADB
2016,2017-01-03,Tỷ lệ thất nghiệp thành thị,3.21,%,ADB
2016,2017-01-03,Tỷ lệ nữ,50.35,%,ADB
2016,2017-01-03,Tỷ lệ nam,49.65,%,ADB
2016,2017-01-03,Tỷ lệ lao động/dân số,57.20,%,ADB
...,...,...,...,...,...
2024,2025-07-13,"Nông, lâm nghiệp và thủy sản",13.67,Triệu người,None
2024,2025-07-06,Dân số,101.30,Triệu người,ADB
2024,2025-07-13,Số lượng lao động,52.90,Triệu người,ADB
2024,2025-07-13,Dịch vụ,20.80,Triệu người,None
2024,2025-07-13,Tỷ lệ thất nghiệp thành thị,2.53,%,ADB

### `retail()`
Fetch Retail sales series.

In [16]:
df_retail = instance.retail()
display(df_retail)

,last_updated,name,value,unit,source
report_time,,,,,
2016-04-30,2016-04-26,TỔNG SỐ:,279806.50,Tỷ VNĐ,Tổng cục thống kê
2016-04-30,2016-04-26,Dịch vụ khác,32984.50,Tỷ VNĐ,Tổng cục thống kê
2016-04-30,2016-04-26,Bán lẻ hàng hóa,214652.10,Tỷ VNĐ,Tổng cục thống kê
2016-04-30,2016-04-26,"Dịch vụ lưu trú, ăn uống",29956.90,Tỷ VNĐ,Tổng cục thống kê
2016-04-30,2016-04-26,Du lịch lữ hành,2213.00,Tỷ VNĐ,Tổng cục thống kê
...,...,...,...,...,...
2026-03-31,2026-04-05,TỔNG SỐ:,638594.08,Tỷ VNĐ,Tổng cục thống kê
2026-03-31,2026-04-05,Bán lẻ hàng hóa,485833.37,Tỷ VNĐ,Tổng cục thống kê
2026-03-31,2026-04-05,"Dịch vụ lưu trú, ăn uống",80309.63,Tỷ VNĐ,Tổng cục thống kê
2026-03-31,2026-04-05,Du lịch lữ hành,7808.00,Tỷ VNĐ,Tổng cục thống kê
2026-03-31,2026-04-05,Dịch vụ khác,64643.07,Tỷ VNĐ,Tổng cục thống kê