# API Adapter - CommodityPrice
Demo tự động các hàm trong class `CommodityPrice`.

In [2]:
from vnstock_data.api.commodity import CommodityPrice

# Khởi tạo instance
instance = CommodityPrice(source='SPL')

### `coke()`
Coke price.

In [3]:
df_coke = instance.coke()
display(df_coke)

              open    high     low   close  volume
time
2025-04-10   99.60   99.60   99.60   99.60    28.0
2025-04-11   99.00   99.00   99.00   99.00    37.0
2025-04-14   99.25   99.25   99.00   99.00   262.0
2025-04-15   99.75  100.50   99.50  100.50    64.0
2025-04-16  100.00  100.00   98.25   98.25    67.0
...            ...     ...     ...     ...     ...
2026-04-06  139.30  139.30  139.30  139.30     0.0
2026-04-07  141.00  142.00  138.00  141.00    95.0
2026-04-08  130.00  132.45  130.00  132.45    58.0
2026-04-09  133.00  134.20  131.50  132.40    78.0
2026-04-10  131.00  131.00  129.00  129.70   198.0

[258 rows x 5 columns]

### `corn()`
Corn price.

In [4]:
df_corn = instance.corn()
display(df_corn)

              open    high     low   close    volume
time
2025-04-10  473.25  484.00  473.00  483.00  257173.0
2025-04-11  482.00  490.75  481.75  490.25  255857.0
2025-04-14  489.00  490.25  484.25  485.00  284335.0
2025-04-15  485.00  488.75  479.00  481.25  201393.0
2025-04-16  481.25  487.00  479.25  484.25  178411.0
...            ...     ...     ...     ...       ...
2026-04-06  453.00  454.50  448.25  454.00  103159.0
2026-04-07  454.00  455.00  448.25  449.00  148547.0
2026-04-08  447.00  448.25  442.25  447.25  256162.0
2026-04-09  447.25  450.25  442.25  444.00  215851.0
2026-04-10  444.75  446.25  438.00  442.00  120865.0

[251 rows x 5 columns]

### `fertilizer_ure()`
Urea fertilizer price.

In [5]:
df_fertilizer_ure = instance.fertilizer_ure()
display(df_fertilizer_ure)

             open   high    low  close  volume
time
2025-04-10  380.0  380.0  380.0  380.0     0.0
2025-04-11  380.0  380.0  380.0  380.0     0.0
2025-04-14  379.0  379.0  379.0  379.0     0.0
2025-04-15  379.0  379.0  379.0  379.0     0.0
2025-04-16  382.5  382.5  382.5  382.5     0.0
...           ...    ...    ...    ...     ...
2026-04-02  750.0  750.0  750.0  750.0     0.0
2026-04-06  752.5  752.5  752.5  752.5     0.0
2026-04-07  795.0  795.0  795.0  795.0     0.0
2026-04-08  795.0  795.0  795.0  795.0     0.0
2026-04-09  795.0  795.0  795.0  795.0     0.0

[237 rows x 5 columns]

### `gas_natural()`
Natural gas price.

In [6]:
df_gas_natural = instance.gas_natural()
display(df_gas_natural)

             open   high    low  close  volume
time
2025-04-10  3.745  3.755  3.465  3.555  7295.0
2025-04-11  3.520  3.575  3.395  3.525  3654.0
2025-04-14  3.490  3.610  3.310  3.325  4555.0
2025-04-15  3.330  3.380  3.215  3.330  3326.0
2025-04-16  3.315  3.315  3.205  3.245  2693.0
...           ...    ...    ...    ...     ...
2026-04-06  2.830  2.865  2.770  2.810  2434.0
2026-04-07  2.800  2.885  2.755  2.870  1889.0
2026-04-08  2.840  2.845  2.700  2.725  3170.0
2026-04-09  2.740  2.755  2.655  2.670  1486.0
2026-04-10  2.670  2.685  2.625  2.670   774.0

[252 rows x 5 columns]

### `gas_vn()`
Vietnam gasoline & diesel prices.

In [7]:
df_gas_vn = instance.gas_vn()
display(df_gas_vn)

            ron95  ron92  oil_do
time
2025-04-10  19.20  18.88   17.24
2025-04-11  19.20  18.88   17.24
2025-04-12  19.20  18.88   17.24
2025-04-13  19.20  18.88   17.24
2025-04-14  19.20  18.88   17.24
...           ...    ...     ...
2026-04-06  27.37  25.42   44.98
2026-04-07  27.37  25.42   44.98
2026-04-08  27.13  24.73   43.24
2026-04-09  24.38  22.34   33.73
2026-04-10  24.38  22.34   33.73

[153 rows x 3 columns]

### `gold_global()`
Global gold price.

In [8]:
df_gold_global = instance.gold_global()
display(df_gold_global)

              open    high     low   close    volume
time
2025-04-10  3099.1  3195.0  3086.1  3177.5  234973.0
2025-04-11  3194.2  3263.0  3193.4  3244.6  247317.0
2025-04-14  3246.0  3261.6  3208.7  3226.3  189619.0
2025-04-15  3226.1  3250.9  3225.5  3240.4  123474.0
2025-04-16  3248.4  3358.4  3245.2  3346.4  258376.0
...            ...     ...     ...     ...       ...
2026-04-06  4675.0  4733.1  4626.2  4684.7   89405.0
2026-04-07  4678.6  4745.7  4631.9  4684.7  143164.0
2026-04-08  4747.2  4888.0  4720.6  4777.2  210080.0
2026-04-09  4744.8  4826.0  4718.6  4818.0  129605.0
2026-04-10  4790.5  4820.0  4752.7  4788.4   88308.0

[252 rows x 5 columns]

### `gold_vn()`
Vietnam gold prices (buy & sell).

In [9]:
df_gold_vn = instance.gold_vn()
display(df_gold_vn)

                 buy      sell
time
2025-04-10  100600.0  103600.0
2025-04-11  102200.0  105200.0
2025-04-12  103000.0  106500.0
2025-04-14  105000.0  107500.0
2025-04-15  105500.0  108000.0
...              ...       ...
2026-04-06  170100.0  173100.0
2026-04-07  169500.0  172500.0
2026-04-08  171000.0  175000.0
2026-04-09  168500.0  171500.0
2026-04-10  169700.0  172700.0

[296 rows x 2 columns]

### `iron_ore()`
Iron ore price.

In [11]:
df_iron_ore = instance.iron_ore()
display(df_iron_ore)

              open    high     low   close  volume
time
2025-04-10   99.89   99.89   99.89   99.89     0.0
2025-04-11   99.95   99.95   99.95   99.95     0.0
2025-04-14  100.08  100.08  100.08  100.08     0.0
2025-04-15  100.19  100.19  100.19  100.19     0.0
2025-04-16  100.08  100.08  100.08  100.08     0.0
...            ...     ...     ...     ...     ...
2026-04-02  107.45  107.45  107.45  107.45     0.0
2026-04-06  107.97  107.97  107.97  107.97     0.0
2026-04-07  108.32  108.32  108.32  108.32     0.0
2026-04-08  107.83  107.83  107.83  107.83     0.0
2026-04-09  106.27  106.27  106.27  106.27     0.0

[250 rows x 5 columns]

### `oil_crude()`
Crude oil price.

In [12]:
df_oil_crude = instance.oil_crude()
display(df_oil_crude)

              open    high     low   close    volume
time
2025-04-10   62.71   63.34   58.76   60.07  391826.0
2025-04-11   60.20   61.87   59.43   61.50  306231.0
2025-04-14   61.70   62.68   60.59   61.53  238068.0
2025-04-15   61.58   62.06   60.88   61.33  197404.0
2025-04-16   61.54   62.98   60.44   62.47  213194.0
...            ...     ...     ...     ...       ...
2026-04-06  112.96  115.48  108.89  112.41  248423.0
2026-04-07  112.62  117.63  109.20  112.95  401381.0
2026-04-08  108.74  109.19   91.05   94.41  562968.0
2026-04-09   96.78  102.70   95.25   97.87  402407.0
2026-04-10   98.23  100.42   97.00   99.07  160410.0

[252 rows x 5 columns]

### `pork_china()`
China live hog price.

In [13]:
df_pork_china = instance.pork_china()
display(df_pork_china)

            close
time
2025-04-15  15.22
2025-04-22  15.29
2025-04-29  15.22
2025-05-06  15.17
2025-05-20  14.93
2025-05-27  14.84
2025-06-03  14.78
2025-06-10  14.58
2025-06-17  14.61
2025-06-24  14.67
2025-07-01  14.96
2025-07-08  15.09
2025-07-15  14.99
2025-07-22  14.86
2025-07-29  14.66
2025-08-19  14.30
2025-08-26  14.22
2025-09-09  14.10
2025-09-23  13.52
2025-10-07  12.90
2025-10-14  12.30
2025-10-21  12.32
2025-11-04  12.71
2025-11-11  12.64
2025-11-18  12.50
2025-11-25  12.33
2025-12-02  12.21
2025-12-09  12.13
2025-12-16  12.16
2025-12-30  12.61
2026-01-06  12.84
2026-01-20  13.39
2026-01-27  13.43
2026-02-03  13.27
2026-02-10  12.94
2026-02-17  12.62
2026-02-24  12.45
2026-03-04  11.89
2026-03-11  11.38
2026-03-24  12.45
2026-03-25  10.68
2026-04-01  10.40

### `pork_north_vn()`
Northern Vietnam live hog price.

In [14]:
df_pork_north_vn = instance.pork_north_vn()
display(df_pork_north_vn)

              close
time
2025-04-10  67500.0
2025-04-13  67600.0
2025-04-14  68200.0
2025-04-15  68400.0
2025-04-16  68600.0
...             ...
2026-03-09  62000.0
2026-03-16  62000.0
2026-03-23  65600.0
2026-03-30  62700.0
2026-04-06  64500.0

[78 rows x 1 columns]

### `soybean()`
Soybean price.

In [15]:
df_soybean = instance.soybean()
display(df_soybean)

               open     high      low    close    volume
time
2025-04-10  1015.25  1029.50  1010.75  1029.00  205523.0
2025-04-11  1026.50  1044.50  1021.75  1042.75  168304.0
2025-04-14  1040.75  1049.50  1036.75  1041.75  191945.0
2025-04-15  1040.50  1041.25  1030.75  1036.00  117322.0
2025-04-16  1046.00  1057.25  1037.50  1050.25  113177.0
...             ...      ...      ...      ...       ...
2026-04-06  1164.50  1169.75  1158.75  1166.75   53402.0
2026-04-07  1164.75  1170.50  1155.25  1158.25   86429.0
2026-04-08  1152.00  1163.00  1140.50  1162.00  118756.0
2026-04-09  1162.00  1170.50  1159.75  1165.25  102746.0
2026-04-10  1166.50  1175.75  1164.50  1175.50   78066.0

[251 rows x 5 columns]

### `steel_d10()`
Vietnam rebar D10 price.

In [16]:
df_steel_d10 = instance.steel_d10()
display(df_steel_d10)

            close
time
2025-04-10  13.60
2025-04-11  13.60
2025-04-12  13.60
2025-04-13  13.60
2025-04-14  13.60
...           ...
2026-04-06  15.43
2026-04-07  15.43
2026-04-08  15.43
2026-04-09  15.43
2026-04-10  15.43

[354 rows x 1 columns]

### `steel_hrc()`
Hot‑rolled coil (HRC) steel price.

In [17]:
df_steel_hrc = instance.steel_hrc()
display(df_steel_hrc)

              open    high     low   close  volume
time
2025-04-10   930.0   930.0   930.0   930.0   428.0
2025-04-11   930.0   950.0   930.0   938.0    29.0
2025-04-14   940.0   940.0   938.0   938.0    10.0
2025-04-15   939.0   940.0   939.0   939.0     4.0
2025-04-16   940.0   940.0   940.0   940.0    41.0
...            ...     ...     ...     ...     ...
2026-04-06  1051.0  1051.0  1049.0  1051.0    11.0
2026-04-07  1048.0  1048.0  1048.0  1048.0    18.0
2026-04-08  1046.0  1046.0  1046.0  1046.0     8.0
2026-04-09  1043.0  1048.0  1043.0  1046.0     2.0
2026-04-10  1048.0  1048.0  1048.0  1048.0     2.0

[251 rows x 5 columns]

### `sugar()`
Sugar price.

In [ ]:
df_sugar = instance.sugar()
display(df_sugar)

             open   high    low  close    volume
time
2025-04-10  18.40  18.50  18.06  18.12  109965.0
2025-04-11  18.10  18.31  17.91  18.00   78004.0
2025-04-14  17.98  18.12  17.81  17.87   52942.0
2025-04-15  17.86  17.95  17.51  17.52   68076.0
2025-04-16  17.57  17.89  17.51  17.86   50318.0
...           ...    ...    ...    ...       ...
2026-04-06  14.92  15.15  14.84  14.97   39386.0
2026-04-07  15.04  15.07  14.57  14.58   92252.0
2026-04-08  14.43  14.51  14.19  14.23  156592.0
2026-04-09  14.25  14.30  13.90  13.92  153556.0
2026-04-10  13.98  14.06  13.80  13.90  104707.0

[251 rows x 5 columns]